export  const ADD_ITEM='ADD_ITEM';
export const ADD_TO_WISH='ADD_TO_WISH';
export const DELETE_ITEM='DELETE_ITEM';
export const DELETE_WISHLIST_ITEM='DELETE_WISHLIST_ITEM';
export const UPDATE_STATUS='UPDATE_STATUS';
export const EDIT_ITEM='EDIT_ITEM';
export const EDIT_ITEM_WISHLIST='EDIT_ITEM_WISHLIST';